### ISSUE TITLE
Feature: new promise function "settle()"

### ISSUE THREAD

**Issue by SimonHeimberg** [reactphp/promise#101]
I need a promise which returns all successful answers and ignoring (or collecting) rejected promises.

A bit like some(), like when.settle https://github.com/cujojs/when/blob/master/docs/api.md#whensettle mentioned in #62

**Comment by jsor** [comment]
This can be accomplished with the available functions and a bit of glue code.

```php
function settle(array $promisesOrValues)
{
    return React\Promise\all(
        array_map(function($promiseOrValue) {
            return React\Promise\resolve($promiseOrValue)->then(
                function ($value) {
                    return [
                        'state' => 'fulfilled',
                        'value' => $value
                    ];
                },
                function ($reason) {
                    return [
                        'state' => 'rejected',
                        'reason' => $reason
                    ];
                }
            );
        }, $promisesOrValues)
    );
}
```

Usage:

```php

$array = [
    React\Promise\resolve('foo'), 
    React\Promise\reject(new \Exception()), 
    'bar'
];

settle($array)->then(function(array $states) {
    print_r($states);
});
```

**Comment by SimonHeimberg** [comment]
Great. Your example works. Thanks. Do not understand how... Anyway.

My next step is to combine this with `React\Promise\Timer\timeout($settlePromises, 5, $loop)`. But I see that I am a newbie and fail there as well. I tried to nest `$settlePromises` into a `Promise(function ($resolve, $reject) {...})` to handle reject myself. Probably wrong, at least it does not work (my reject is not called).
My current workaround is to collect the return values in ->then() of the original $promises.
```php
foreach($promises as $promise) {
    $promise->then(function ($v) use ($collectedV) {
        $collectedV[] = $v;
    });
}
$settlePromises = settle($promises );
...
```

Shall I ask this question on https://github.com/reactphp/promise-timer ?
What I finally would like is a function awaitSuccessful() in https://github.com/clue/php-block-react/ . I currently try to write it in my code.

**Comment by jsor** [comment]
Maybe you should describe your actual use case and what you're trying to achieve.

1. Option: add a timeout the returned promise from `settle()`.

```php
$promises = [/* ... */];

$settlePromises = settle($promises);

$timeoutPromise = timeout($settlePromises, 10.0, $loop);

$timeoutPromise->then(
    function (array $states) {
        // All promises fulfilled or rejected within 10 sec.
    },
    function (Timer\TimeoutException $e) {
        // At least one of $promises didn't resolve within 10 sec.
    }
);
```

2. Option: apply a timeout to each input promise. That requires a modified `settle()`:

```php
function settleWithTimeout(array $promisesOrValues, $timeout, $loop)
{
    return React\Promise\all(
        array_map(function($promiseOrValue) use ($timeout, $loop) {
            $promise = React\Promise\Timer\timeout(
                React\Promise\resolve($promiseOrValue),
                $timeout,
                $loop
            );

            return $promise->then(
                function ($value) {
                    return [
                        'state' => 'fulfilled',
                        'value' => $value
                    ];
                },
                function ($reason) {
                    return [
                        'state' => 'rejected',
                        'reason' => $reason
                    ];
                }
            );
        }, $promisesOrValues)
    );
}

$settlePromises = settle($promises);

$settlePromises->then(function(array $states) {
    foreach ($states as $state) {
        $didPromiseTimedout = (
            $state['state'] === 'rejected' &&
            $state['reason'] instanceof React\Promise\Timer\TimeoutException
        );
    }
});
```

**Comment by SimonHeimberg** [comment]
I want to use `Clue\React\Buzz\Browser` for doing several requests in parallel. For collecting the results I used `Clue\React\Block\awaitAll()`. But this only returns  (as the name says) if **all** requests are successful. What I want is the successful responses. (To get the failing responses is a plus, since it allows things like logging.)

**Comment by jsor** [comment]
You only need to await the last promise. For option 2 from my last [comment](https://github.com/reactphp/promise/issues/101#issuecomment-331414582) it's

```php
$states = Block\await(
    settleWithTimeout($promises, 10, $loop), 
    $loop
);

$timedOutStates = array_filter($states, function (array $state) {
    return (
        $state['state'] === 'rejected' &&
        $state['reason'] instanceof React\Promise\Timer\TimeoutException
    );
});

$successfulStates = array_filter($states, function (array $state) {
    return $state['state'] === 'fulfilled';
});

$successfulValues = array_map(function (array $state) {
    return $state['value'];
}, $successfullStates);
```

**Comment by SimonHeimberg** [comment]
thanks.
(I guessed that one timer should be enough to cancel all pending promises. But I prefer running code for sure.)

Would it make sense to add `settle(...)` into `React\Promise`? (maybe with a boolean instead of string for state)
Would it make sense to add `settleWithTimeout(...)` to https://github.com/reactphp/promise-timer?

**Comment by jsor** [comment]
Those are perfect candidates for a third-party utility package. Bonus points: it could support multiple version of `react/promise`.

**Comment by SimonHeimberg** [comment]
third-party utility package: https://github.com/EmchBerger/react-settle-promise
any feedback before I tag a version?

**Comment by jsor** [comment]
@SimonHeimberg Awesome! Added a few comments to the initial commit. 👍

**Comment by WyriHaximus** [comment]
@SimonHeimberg awesome! Don't forget to add it to: https://github.com/reactphp/react/wiki/Users

**Comment by jsor** [comment]
I think this has been resolved 👍

**Comment by ellisonpatterson** [comment]
Could this possibly be considered for the current release of Promises, as it really would be helpful.

Thank you!
