### ISSUE TITLE
Examples for writing unit tests?

### ISSUE THREAD

**Issue by norbert-yoimo** [reactphp/promise#103]
I'm trying to write a unit test for code that uses Promises. I looked at the tests in this project, but I can't figure out what's happening, I was expecting to see some reference to an event loop, that I can block on, but it seems like no such things are happening?

How can I make PHPUnit block/wait until my promises resolve? For example, see the following test:

```php
    public function testPromises() {
        $promise = new Promise(function() {
            return ['hello' => 'world'];
        });
        $promise->then(function($result) {
            $this->assertArrayHasKey('hello', $result);
        });
    }
```

This fails with the error "This test did not perform any assertions", which is expected, since nothing is blocking execution until the promise resolves.

How can I block PHPUnit until my promises resolve?

**Comment by kelunik** [comment]
That test shouldn't result in "This test did not perform any assertions" as `then()` callbacks are called immediately. If you want to run the event loop until the a promise resolved, you can use https://github.com/clue/php-block-react.

**Comment by norbert-yoimo** [comment]
Hmm, I get:

```
PHPUnit 6.3.0 by Sebastian Bergmann and contributors.

R                                                                   1 / 1 (100%)

Time: 172 ms, Memory: 6.00MB

There was 1 risky test:

1) Tests\YoimoComBundle\RecordingTest::testPromises
This test did not perform any assertions
```

Installed versions:
```
react/promise                      v2.5.1             A lightweight implementation of CommonJS Promises/A for PHP
phpunit/phpunit                    6.3.0              The PHP Unit Testing framework.
```

**Comment by jsor** [comment]
The promise isn't resolved correctly and the callback passed to `then()` isn't called.

```php
$promise = new Promise(function($resolve) {
    $resolve(['hello' => 'world']);
});
```

Other than that, if you expect the promise to be resolved async, you can use https://github.com/clue/php-block-react as @kelunik suggested. 👍

**Comment by kelunik** [comment]
Whoops, good catch, @jsor. :+1:

**Comment by norbert-yoimo** [comment]
My bad, sorry, it works :/

Thank you @kelunik and @jsor.
