### ISSUE TITLE
Mark promise progress / notify() as deprecated for Promise v2

### ISSUE THREAD

**Issue by clue** [reactphp/promise#108]
The promise progress / notify() API is deprecated and has been removed with the upcoming Promise v3 release (see #32). There's currently no schedule as to when this version is going to be released.

The current documentation for Promise v2 should include a deprecation notice to discourage people from relying on this API.

**Comment by slash3b** [comment]
@clue could you please check https://github.com/reactphp/promise/pull/109 ?

**Comment by clue** [comment]
Closed via #112
