### ISSUE TITLE
example no works 

### ISSUE THREAD

**Issue by StasToken** [reactphp/promise#127]
hello example no works  

> require './vendor/autoload.php';
> function getAwesomeResultPromise()
> {
>     $deferred = new React\Promise\Deferred();
>     // Execute a Node.js-style function using the callback pattern
>     computeAwesomeResultAsynchronously(function ($error, $result) use ($deferred) {
>         if ($error) {
>             $deferred->reject($error);
>         } else {
>             $deferred->resolve($result);
>         }
>     });
> 
>     // Return the promise
>     return $deferred->promise();
> } getAwesomeResultPromise()
>     ->then(
>         function ($value) {
>             // Deferred resolved, do something with $value
>         },
>         function ($reason) {
>             // Deferred rejected, do something with $reason
>         }
>     );

Error:

> PHP Fatal error:  Uncaught Error: Call to undefined function computeAwesomeResultAsynchronously() in /tmp/proc/promise/test.php:8
> Stack trace:
> #0 /tmp/proc/promise/test.php(20): getAwesomeResultPromise()
> #1 {main}
>   thrown in /tmp/proc/promise/test.php on line 8

I take an example from the readme example and it does not work why?

**Comment by swapnilkuwar** [comment]
You have to implement the computeAwesomeResultAsynchronously function to work this example.
