### ISSUE TITLE
Promises do not throw unhandled exceptions

### ISSUE THREAD

**Issue by SerafimArts** [reactphp/promise#128]
It seems to me that all unhandled exceptions (for example, without `->otherwise`) should be thrown out but this does not happen. Those. In fact, any exceptions impossible to intercept.

I will cite as an example another language where such a class is already implemented and where behaviour is different.

## Code sample

ReactPHP (~2.7)

```php
use React\Promise\Deferred;

$deferred = new Deferred();

$deferred->promise()->then(function(): void {
    throw new \Exception('Example');
});

$deferred->resolve();
```

A similar JS example:

```js
let p = new Promise((c) => {
  setTimeout(() => c(), 1000);
});

p.then(() => { throw new Error(); });
```

## Expected

```
Uncaught Exception: Example in ...
```

## Actual

**ReactPHP**: Nothing

**JS**: `Uncaught (in promise) Error ...`

**Comment by szymon-podeszwa** [comment]
Why this ticket was closed? This behavior is intentional?

**Comment by WyriHaximus** [comment]
@szymon-podeszwa `done` rethrows unhandled promises:

```php
use React\Promise\Deferred;

$deferred = new Deferred();

$deferred->promise()->then(function(): void {
    throw new \Exception('Example');
})->done();

$deferred->resolve();
```

**Comment by clue** [comment]
Duplicate of #87
