### ISSUE TITLE
return promise from onFullfilled

### ISSUE THREAD

**Issue by ozeals** [reactphp/promise#146]
#### Sample 1
```php
$defered = new Deferred();

$defered->promise()->then(function($promise){

    var_dump($promise);

});

$done = new Promise(function($resolve){
    $resolve('done');
});


$defered->resolve($done);
```
results
```
string(4) "done"
```

#### Sample 2
```php
$defered = new Deferred();

$defered->promise()->then(function($promise){

    var_dump($promise);

});


$defered->resolve('done');
```
results
```
string(4) "done"
```

#### Expected behavior
```sample 1``` I expected resolved value of the then onFullfiled to be instance of Promise not its resolved value (promise)..

```sample 2``` works as expeced

#### intended use case
```php
$defered = new Deferred();

$defered->promise()->then(function($promise){
    $defered = new Deferred();
    $promise->then(function($databasevalue) use ($defared) {
        $proccessedlogentries = 'proccessed-log-entries';
        $defered->resolve($proccessedlogentries);
        
    });
    return $defered->promise();
})->then(function($logentriespromise){
    //... blah blah blah
});

$done = new Promise(function($resolve){
    $somedatabasevalue = 'database-value';
    $resolve($somedatabasevalue);
});

$defered->resolve($done);
```
I like to be in controll of when my promise blocks and when it just a waiting passthrough since some promises will be resolve on different event loop ticks

My current state is rewriting promise from ground up or maybe i missed somthing on how to mentain my promise from being unwraped by the onFullfilled method

**Comment by ozeals** [comment]
Some help please me before i start trying to reinvent the promise wheel...!

**Comment by clue** [comment]
Hi @ozeals, welcome to the wonderful world of promises!

What you're seeing is expected behavior, the promise will "follow" the given promise and the child promise will automatically settle when the parent promise settles. See also https://github.com/reactphp/promise#deferredresolve.

The way I understand your code it means that you should simply await the resolution *value* instead of waiting for a promise to resolve with another promise. In other words, instead of this

```php
$defered->promise()->then(function($promise){
    $defered = new Deferred();
    $promise->then(function($databasevalue) use ($defared) {
        $proccessedlogentries = 'proccessed-log-entries';
        $defered->resolve($proccessedlogentries);
        
    });
    return $defered->promise();
})->then(function($logentriespromise){
    //... blah blah blah
});
```

do this instead:

```php
$defered->promise()->then(function ($databasevalue) {
    $proccessedlogentries = 'proccessed-log-entries';
    return $processedlogentries;
})->then(function($logentriesvalue){
    //... blah blah blah
});
```

I hope this helps :+1:

**Comment by ozeals** [comment]
Thanks @clue for the enlightenment.. But that would mean the Promise works exactly like a pipe line.. right!!. okay say i want to resolve ```proccessedlogentries``` on the event loop like

```php
$defered->promise()->then(function($promise) use ($loop) {
    $defered = new Deferred();
    $loop->furturTick(function() use ($defered){
        $proccessedlogentries = 'proccessed-log-entries';
        $defered->resolve($proccessedlogentries);
    });
    return $defered->promise();
})->then(function($logentriespromise){
    // this then function is never called
    //... blah blah blah
})->then(function(){
    // this then function is never called too
});
``` 

I was thinking of trying this
```
class PromiseWrapper
{
    proctected $wraped;
    
    public function __construct($promise)
    {
        $this->wraped = $promise;
    }
    
    public function promise()
    {
        return $this->wraped;
    }
    
    public static function wrap($promise)
    {
         return new static($promise);
    }

}
````

##### resolve
```php
$done = new Promise(function($resolve){
    $somedatabasevalue = 'database-value';
    $resolve($somedatabasevalue);
});

$defered->resolve(PromiseWraper::wrap($done));
```

but it seams kinda ```hacky```

**Comment by ozeals** [comment]
The wraping of the promise makes prefect sence but Promise will be EXACTLY like a pipeline.. instead of being able to defer deferent steps of the then execution to something like an event loop...

```
[resolve-promise]->then[sched on futureTick]->then[shed on futureTick]->then[results]
```
That will make more sence for unwraping the promise and be truely async.

**Comment by clue** [comment]
@ozeals I'm not sure I follow exactly what you're trying to achieve here, but your first example looks almost good. It looks like you've misspelled `$loop->futureTick()` in there which will throw a `Throwable` on PHP7+ which will reject your promise. This explains why your resolution handlers will not be called anymore. You should add a rejection handler (second argument to then), for testing purposes I often play around with this like this:

```
$promise->then('var_dump', 'printf');
```

I'm not sure what you mean by your pipeline analogy, but I guess it might make sense if you prefer to view it as such.

**Comment by ozeals** [comment]
@clue sry about the typo.. My goal is resolve then resolver on the event loop like 

```php
$defered->promise()->then(function($promise) use ($loop) {
    $defered = new Deferred();
    $loop->futurTick(function() use ($defered){
        $proccessedlogentries = 'proccessed-log-entries';
        $defered->resolve($proccessedlogentries);
    });
    return $defered->promise();

})->then(function($logentriesresults) use ($loop) {

    $defered = new Deferred();
    $loop->futurTick(function() use ($defered, $logentriesresults){
        $longtask = "done some other long taks with [$logentriesresults]";
        $defered->resolve($longtaks);
    });
    return $defered->promise();

})->then(function(){
    // this then function is never called too
});
```
Say each then function takes a long time to run.. Having them all run syncronosly in series when the first promise is resolved is not ideal for me. But having each then function shedule some futureTick taks on the event loop then resolve its results to the next then function is true async. I don't care how long each then function takes once its starts i just dont want them running synchronously in series after the first resolve but rather asynchronously in series

**Comment by ozeals** [comment]
Thanks for the help @clue.

**Comment by clue** [comment]
Your last example still has a typo that will cause this `Throwable`, perhaps try it like this:

```php
$defered->promise()->then(function($promise) use ($loop) {
    $defered = new Deferred();
    $loop->futureTick(function() use ($defered){
        $proccessedlogentries = 'proccessed-log-entries';
        $defered->resolve($proccessedlogentries);
    });
    return $defered->promise();

})->then(function($logentriesresults) use ($loop) {

    $defered = new Deferred();
    $loop->futureTick(function() use ($defered, $logentriesresults){
        $longtask = "done some other long taks with [$logentriesresults]";
        $defered->resolve($longtaks);
    });
    return $defered->promise();

})->then(function(){
    // this then function is never called too
})->then('var_dump', 'printf'); // will dump the results or print any exception
```

The above code should work or at least help you diagnose why it doesn't. That being said, it sounds like promises may not be the best tool for what you're trying to achieve. Instead of breaking a blocking application into smaller parts, have you considered going fully non-blocking? This works for pretty much any I/O operation, such as HTTP or database calls etc., but less so for CPU intensive operations (which most PHP applications do not tend to be).
