### ISSUE TITLE
ETA version 3?

### ISSUE THREAD

**Issue by Ilyes512** [reactphp/promise#166]
Hi,

I was wondering if there is some kind of a schedule or plan for version 3. It seems to have quite some performance fixes (the stack thing). It also seems to be more than a year ago?

**Comment by WyriHaximus** [comment]
We're making sure all our own packages are compatible with v3 before releasing it.

**Comment by Ilyes512** [comment]
Okey. Sounds logical. Do you guys perhaps keep a (progress) board somewhere?

**Comment by WyriHaximus** [comment]
These are the PR's: https://github.com/search?q=is%3Aopen+is%3Apr+author%3AWyriHaximus+archived%3Afalse+org%3Areactphp+%22react%2Fpromise+3%22

**Comment by Ilyes512** [comment]
Ah nice :) I will close this now.
