### ISSUE TITLE
allSettled operator

### ISSUE THREAD

**Issue by andrei115** [reactphp/promise#194]
In my use case I would want to have the functionality of the all() operator, but not have the promise rejected if one of the promises fails.
I've seen in javascript the operator for this is called allSettled(). Is there anything similar that I could?

**Comment by WyriHaximus** [comment]
Should be possible, what would you do with the rejected promises? Just don't care about those?

**Comment by andrei115** [comment]
found it, it's the GuzzleHttp\Promise\Utils::settle() method. 

I had some messages from a message queue that needed processing. After completing the processing, I needed to inform the queue which messages were processed correctly so that it wouldn't deliver those messages anymore.
