### ISSUE TITLE
QUESTION - How to test if a code is blocking or not

### ISSUE THREAD

**Issue by eemmy** [reactphp/promise#203]
Hi, i'm starting to work with Async PHP now, and i'm not certain how to test if a function/code block is blocking or non-blocking, someone can teach me how i do that?

Sorry for poor english.

**Comment by WyriHaximus** [comment]
In short, any function that does I/O or `sleep` is blocking, and you should use the `ReactPHP` alternative for it.

**Comment by clue** [comment]
What @WyriHaximus said ☝️

For starters, any function that can take longer than ~1ms should be considered blocking. This includes all functions that perform some kind of I/O, such as sending an HTTP request or a database query. The good news is that ReactPHP already provides alternatives for many common requirements, such as an [HTTP client](https://github.com/reactphp/http) or [MySQL database adapter](https://github.com/friends-of-reactphp/mysql). See also our wiki for a more comprehensive list of non-blocking adapters: https://github.com/reactphp/reactphp/wiki/Users

I hope this helps! :+1: I believe this has been answered, so I'm closing this for now. Please come back with more details if you feel there's anything to add and we can always reopen this :+1:
