### ISSUE TITLE
Cannot redeclare React\Promise\resolve()

### ISSUE THREAD

**Issue by schmunk42** [reactphp/promise#23]
Hi,

we stumbled over this issue today:

```
PHP Fatal error:  Cannot redeclare React\Promise\resolve() (previously declared in /root/.composer/vendor/react/promise/src/functions.php:5) in /app/vendor/react/promise/src/React/Promise/functions.php on line 12
PHP Fatal error:  Cannot redeclare React\Promise\resolve() (previously declared in /root/.composer/vendor/react/promise/src/functions.php:5) in /app/vendor/react/promise/src/React/Promise/functions.php on line 12
[...]
```

We have a composer packages installed globally and per project which both depend on `react/promise`.

I think the composer autoloader always loads the file specified [here](https://github.com/reactphp/promise/blob/master/composer.json#L15) which looks to me like the source of the error.

I don't know if composer should handle that...

You could wrap the definitions in a `function_exists()` call if you have to use the legacy `files` autoloading.

**Comment by bhajan903** [comment]
hey ,
how solved this 
"Sorry, that didn’t work.
Please try again or come back later.
500 Error. Internal Server Error."
please!

**Comment by WyriHaximus** [comment]
@bhajan903 check your server logs, that error is so generic we can't do anything with it. Also please open a new ticket for if the error is ReactPHP.
