### ISSUE TITLE
Add example folder

### ISSUE THREAD

**Issue by ishanvyas22** [reactphp/promise#232]
It would be good to have `examples` folder in the repo same as there's for others like [reactphp/filesystem](https://github.com/reactphp/filesystem/tree/0.2.x/examples). 

Examples can be how to read file using promises or any other real world use case.

**Comment by WyriHaximus** [comment]
While I agree with having some examples there so users can play around with it. Examples like reading a file are better suited in the package that provides that functionality. Promises are a rather low-level package so most examples will and should be rather abstract. Where as the filesystem package or HTTP package should have examples on how to make HTTP requests or read from a file.

**Comment by clue** [comment]
I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:
