### ISSUE TITLE
oop(s)

### ISSUE THREAD

**Issue by jarnix** [reactphp/promise#26]
I don't understand the point of having namespaces and oop if we need to require a file having functions defined globally like in functions.php
```php
<?php

if (!function_exists('React\Promise\resolve')) {
    require __DIR__.'/functions.php';
}
```

**Comment by jsor** [comment]
All functions are under the `React\Promise` namespace and the file must be required we don't have function autoloading (yet) in PHP. This particular code is a workaround, see #23.
