### ISSUE TITLE
Call to undefined function React\Promise\resolve()

### ISSUE THREAD

**Issue by ankitapage** [reactphp/promise#29]
Hi,
I got the error "Call to undefined function React\Promise\resolve()" and its in file "FatalErrorException in Promise.php line 128".
Can you please tell me what is causing this error.

Thanks.

**Comment by jsor** [comment]
Resolved in [#27](https://github.com/reactphp/promise/issues/27#issuecomment-106766947)

**Comment by ManuelVR461** [comment]
tengo el siguiente error al intentar conectarme a servicio socket creado con ratchet:  PHP Fatal error:  Uncaught Error: Call to undefined function React\Promise\reject(). revise el codigo y dentro de las clases veo que llaman en metodo reject sin la preposion $this-> esto es correcto?  quien me puede ayudar al respecto?
