### ISSUE TITLE
Deferred is an anti-pattern

### ISSUE THREAD

**Issue by ojhaujjwal** [reactphp/promise#30]
Read this:
https://github.com/petkaantonov/bluebird/wiki/Promise-anti-patterns#the-deferred-anti-pattern

**Comment by daltones** [comment]
~~Deferred is an anti-pattern.~~

There are *some* deferred anti-patterns. The article even gives a good use case.

**Comment by WyriHaximus** [comment]
What is your goal with this issue? If it's educating users (what I fully support) why not consider making a PR for the readme adding a small anti-patterns section. Have a chat with @jsor about it first and I think you can come up with something :+1: .

**Comment by jsor** [comment]
Closing this for now. Feel free to reopen or start a discussion in a new issue/pr.
