### ISSUE TITLE
[RFC] Deprecate promise progress API

### ISSUE THREAD

**Issue by clue** [reactphp/promise#32]
This ticket serves as a basis for discussing deprecating the promise progress API.
This has come up quite a few times.

As a first step, this ticket aims to *only deprecate* the existing functionality and update the documentation accordingly. At a later stage, we *should* consider *dropping* the functionality altogether (BC break ahead).

Opening this ticket as an RFC and for the reference.

**Comment by jsor** [comment]
References of JS promise libraries deprecating the progression API:

* https://github.com/petkaantonov/bluebird/blob/master/API.md#progression-migration
* https://github.com/cujojs/when/blob/master/docs/api.md#promiseprogress

**Comment by jsor** [comment]
I'm planning to remove the progression API for 3.0.

**Comment by clue** [comment]
:+1:
