### ISSUE TITLE
Validate array argument for promise-array related functions

### ISSUE THREAD

**Issue by jsor** [reactphp/promise#35]
Reject all() / race() / any() / some() / map() / reduce() when called with a non-array.

```php
all(null)
    ->otherwise(function(\InvalidArgumentException $e) {
        assertEquals('Expecting an array or a promise which resolves to an array, got NULL instead.' , $exception->getMessage());
    });
```

**Comment by clue** [comment]
:+1: for rejecting invalid input

But then again *what* is valid input here? :-)

**Comment by jsor** [comment]
At the moment, it is an array or a promise which resolve to an array. Passing anything other produces

```php
all(null)
    ->then(function($value) {
        assertEquals([], $value);
    });
```

which i think is not an expected behaviour.

**Comment by clue** [comment]
> which i think is not an expected behaviour

Yeah, I agree that we should handle this is in a more sane way :+1: 

However, now that we're already considering *what* is valid input, I would suggest using a stricter definition. For example, ES6-style promises limit the parameter to be an array of promises (or values which are considered like resolved promises): https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Promise/all (which IMHO makes sense to me).

As such, does it make sense to pass a single Promise which resolves to an array of values? Do we have a valid use case for this?

**Comment by jsor** [comment]
> As such, does it make sense to pass a single Promise which resolves to an array of values? Do we have a valid use case for this?

I've never used a single input promise.

Options:
* No change, allow input promise which resolves to an array, requires rejection with InvalidArgumentException for non-array input
* Typehint against `array`, does **not** require rejection for non-array input
* Allow `array` **and** `\Traversable` input, no typehint possible, requires rejection with InvalidArgumentException for non-array input

I'm unsure on this atm.

**Comment by clue** [comment]
> No change, allow input promise which resolves to an array, requires rejection with InvalidArgumentException for non-array input

:-1: on this unless we find a valid use case

> *    Typehint against array, does not require rejection for non-array input
*    Allow array and \Traversable input, no typehint possible, requires rejection with InvalidArgumentException for non-array input

IMO both sound sane…

Some (random) thoughts:

* On success, the `all()` method resolves with an `array`, so for consistency it may make sense to require an input `array`
* `Traversable` and `Iterator` have valid use cases, though I'm failing to see how these would be beneficial here. Also, converting via `iterator_to_array()` is trivial.
* Permitting several input types means we have to use additional runtime checks which add to complexity. Also, this makes it harder to use type guessing (IDEs).
* Typehinting against `array` is trivial and requires no boilerplate. It probably fulfills 80%+ of the use cases anyway and converting to an array is trivial.

As such, I'm leaning towards using an `array` typehint :+1:

**Comment by jsor** [comment]
> As such, I'm leaning towards using an array typehint
:+1:
