### ISSUE TITLE
PHP Syntax Error in src/functions.php

### ISSUE THREAD

**Issue by NicholasRBowers** [reactphp/promise#38]
Parse error: syntax error, unexpected '[', expecting ')' in CODE on line 68.

**Comment by jsor** [comment]
This is the short array syntax introduced in PHP 5.4 which React/Promise requires as [minimum version](https://github.com/reactphp/promise/blob/master/composer.json#L9). Looks like you're running PHP 5.3?

**Comment by jsor** [comment]
If you're stuck with PHP 5.3, you can use React/Promise ~1.1 which lately got a [compatibility update](https://github.com/reactphp/promise/releases/tag/v1.1.0).

**Comment by NicholasRBowers** [comment]
I literally just noticed that I didn't change the PHP version on my local machine.  Such a false alarm.

**Comment by jsor** [comment]
No problem :smile:
