### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by steved1982** [reactphp/promise#42]
<b>Parse error</b>:  syntax error, unexpected '[' in <b>/home/seewhaty/public_html/site/vendor/react/promise/src/functions.php</b> on line <b>75</b>

**Comment by steved1982** [comment]
I get this issue when just loading my autoload file on the site, not doing any calls yet.

**Comment by WyriHaximus** [comment]
You're trying to run 2.x which is for PHP5.4 to run in PHP5.3 or lower. 1.x is PHP5.3 compatible.

**Comment by steved1982** [comment]
Thank you, I managed to get the site upgraded to PHP5.4 and it works now.
