### ISSUE TITLE
Support foreign thenables in resolve()

### ISSUE THREAD

**Issue by jsor** [reactphp/promise#45]
Allow foreign promises to be turned into trusted promises by checking `method_exists($promiseOrValue, 'then')`.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/resolve

**Comment by clue** [comment]
:+1: Trivial implementation and huge step for interoperability with non-react libs

**Comment by jsor** [comment]
Released in [v2.4.0](https://github.com/reactphp/promise/releases/tag/v2.4.0).
