### ISSUE TITLE
React\Promise\FulfilledPromise Object 

### ISSUE THREAD

**Issue by victorgp89** [reactphp/promise#58]
Hi, 

I create a promise like this: 

```
public function callService($condition) {
        $deferred = new \React\Promise\Deferred();
        
        $this->callApi($condition, function($result) use ($deferred) {
            if (empty($result)) {
                $deferred->reject(new \Exception('No prices available!'));
            } else {
                $deferred->resolve($result);
            }
        });

        return $deferred->promise();
}
```

And in the return of the promise: 

```
return $this->callService($condition)
    ->then(
        function($prices) {   
                return $prices;
        },
        function(\Exception $e) {
                return $e->getMessage();
        }
    );
```
It return a FulfilledPromise with private value. How can I return only the value of prices? 

Thanks for advance.

**Comment by jsor** [comment]
You cannot return the value directly from asynchronous operations. That's what Promises are for. They act as a placeholder for the return value which might be only available in the future.

```
return $this->callService($condition)
    ->then(
        function($prices) {   
            // Do something with $prices
        },
        function(\Exception $e) {
            // Handle error here
        }
    );
```

**Comment by victorgp89** [comment]
In the case that don't need do anything with prices and only want to the return value. It's no possible? 

And with the return value (is array) I want to iterate it asynchronous to make some filters.

**Comment by jsor** [comment]
I'm not sure i understand the question. You have to do anything you want to do once the promise resolved inside the `$onFulfilled` callback of `then`.

```
return $this->callService($condition)
    ->then(
        function($prices) {   
            // -> here
        }
    );
```

**Comment by jsor** [comment]
Closing for now, feel free to reopen if you have any further questions.
