### ISSUE TITLE
How i can throw Exception from onRejected callback?

### ISSUE THREAD

**Issue by maxgu** [reactphp/promise#59]
my code:
```php
RatchetClient\connect("ws://{$this->host}:{$this->port}")->then(function(WebSocket $conn) use ($event, $data) {
    $conn->on('message', function($msg) use ($conn) {
        $conn->close();
    });

    $conn->send(json_encode(['event' => $event, 'data' => $data]));
}, function ($e) {
    // this exception never called, somebody catch it
    throw new RuntimeException("Could not connect: {$e->getMessage()}\n");
});
```
If my websocket server not running - nothing happen, i want see exception and stop execution.
How i can throw Exception from onRejected callback?

**Comment by jsor** [comment]
Use [`done`](https://github.com/reactphp/promise#extendedpromiseinterfacedone) instead of `then`. Read also [done() vs. then()](https://github.com/reactphp/promise#done-vs-then).

**Comment by maxgu** [comment]
ok, thnx
