### ISSUE TITLE
exception in promise

### ISSUE THREAD

**Issue by socketman2016** [reactphp/promise#63]
How can l throw an uncaught exception onRejected?
I try then and done but no difference.
```php
$promise->then(null, function (){
    throw new Exception;
});
```

```php
$promise->done(null, function (){
    throw new Exception;
});
```

**Comment by jsor** [comment]
You need to call `done()` on the promise returned by `then()`.

```php
$promise
    ->then(null, function (){
        throw new Exception;
    })
    ->done()
;
```

**Comment by socketman2016** [comment]
Not working for me! why?
I check my code there is no try catch block in my codes!

**Comment by socketman2016** [comment]
I understand who catch my exception
react/promise/src/FulfilledPromise.php:26
Why? How can I prevent it
```php
        try {
            return resolve($onFulfilled($this->value));
        } catch (\Throwable $exception) {
            //Catched Here
            return new RejectedPromise($exception);
        } catch (\Exception $exception) {
            return new RejectedPromise($exception);
        }
```

**Comment by socketman2016** [comment]
Any idea?

**Comment by jsor** [comment]
The code is probably wrapped into another promise which catches the exception. You must ensure that you call `done()` on any promise which you don't return for comsumption from a function. See [done() vs. then()](https://github.com/reactphp/promise#done-vs-then).

**Comment by socketman2016** [comment]
Please see https://github.com/jakubkulhan/bunny/issues/36 maybe you can help me

**Comment by jsor** [comment]
I've opened jakubkulhan/bunny#37 which should fix this.

**Comment by socketman2016** [comment]
thanks a lot
