### ISSUE TITLE
Interoperability Implementation

### ISSUE THREAD

**Issue by kelunik** [reactphp/promise#64]
Do you plan to implement https://github.com/async-interop/awaitable? Would you mind to provide feedback?

**Comment by jsor** [comment]
I'm planning to support at least consuming awaitables through [`resolve`](https://github.com/reactphp/promise#resolve).

What kind of feedback would you like to have and where? Any specific issues or just general feedback?

**Comment by kelunik** [comment]
Mostly general feedback whether it's fine in the current state. Most actively involved people come from Icicle and Amp, would be good to have also feedback from React.

The signature should be compatible, I hope the order requirements and other requirements are compatible as well.

**Comment by jsor** [comment]
The only problem i see is the requirement of an event loop implementation. React/Promise doesn't require an event loop. I fear this will block us from implementing the interface directly.

Will there be a test suite like the one for the [event loop](https://github.com/async-interop/event-loop-test)?

**Comment by kelunik** [comment]
I don't know whether we can provide a test suite, as the interface only standardizes how promises / awaitables can be consumed, not how they're resolved.

> React/Promise doesn't require an event loop. I fear this will block us from implementing the interface directly.

That might indeed be an issue. If you can't implement the interface directly, I guess we have to live with adapter functions. React doesn't have the issue with the callbacks throwing, as that just fails the returned promise. /cc @bwoebi

**Comment by bwoebi** [comment]
Regarding the event loop, we can just make the behavior undefined in case it's lacking. Thus, React can handle it it's own way if there's no event-loop. If people use `when()` with no event loop driver factory registered, it's their fault.

@jsor À propos tests, how can we test an interface with only a mere callback registering method, as the interface doesn't specify a way to trigger the callbacks?

**Comment by jsor** [comment]
The introduction of a task queue in 3.0 (which defaults to a synchronous implementation but can be replaced with an event loop based implementation) will probably solve this.

Regarding the tests: I thought about something like the [Promises/A+ Compliance Test Suite](https://github.com/promises-aplus/promises-tests) where you can provide an [adapter](https://github.com/promises-aplus/promises-tests#adapters) and then validate if your implementation complies with the spec.

**Comment by bwoebi** [comment]
Okay, I'll give the task queue a look this evening.

**Comment by bwoebi** [comment]
@jsor Turns out "This evening" was a bit too ambitious :-P

Anyway, here it is: https://github.com/async-interop/awaitable-test - I hope this suits your needs? (The loop is optional and just needed for one test, which is skipped if driver set to null)

**Comment by jsor** [comment]
@bwoebi Great, thanks! I will look into it and see if we can consider implementing Awaitable directly for 3.0.

**Comment by jsor** [comment]
I've done an implementation for 2.x if anyone wants to review: https://github.com/reactphp/promise/compare/2.x...2.x-async-interop

@bwoebi I've copied your tests over because your repository is still using `Awaitable` instead of `Promise`.

**Comment by kelunik** [comment]
Closing as no longer relevant. Amp v2 will have built-in support for React's promises, maybe React wants to do something similar, but that should be discussed in a separate issue.
