### ISSUE TITLE
Resolve before returning?

### ISSUE THREAD

**Issue by g105b** [reactphp/promise#65]
Here is a contrived example of a promise that is resolved before being used.

```php
function do_something() {
    $deferred = new Deferred();
    $deferred->resolve(true);
    return $deferred->promise();
}

do_something()->then(function() {
    // This is never called, because the resolution has occurred before the call to then.
});
```

Can anyone suggest a way of using this code in the current release? If not, does anyone have any suggestions to the implementation? My thoughts are to check if the promise is resolved _within_ the `then` call, and if so, call the `onFulfilled` function automatically.

**Comment by jsor** [comment]
What makes you think the `onFulfilled` handler isn't called? Handlers will be invoked before and after resolution.

**Comment by g105b** [comment]
I had the false assumption because of the way I'm using this library in my project. Extra logic is muddying the waters as to why I can't do what I'm expecting.

For clarification in case anyone else is interested:

```php
<?php
require "vendor/autoload.php";

$defer = new React\Promise\Deferred();
$promise = $defer->promise();

$defer->resolve("I'm done!");

$promise->then(function($result) {
    echo $result . PHP_EOL;
});

echo "EOF";
```

Output:

```
I'm done!
EOF
```

Even though the deferred is resolved before the promise's then function is called.
