### ISSUE TITLE
guzzle/promises

### ISSUE THREAD

**Issue by socketman2016** [reactphp/promise#66]
How can I convert guzzle/promises to reactphp/promise ?
As there is no ```done()``` method for guzzle/promises , I want to convert it to reactphp/promise 

```php

// $guzzlePromise is an instance of GuzzleHttp\Promise\Promise and is a result of third party library
$reactPromise = convert($guzzlePromise);
```

**Comment by WyriHaximus** [comment]
Using `react/promise` `^2.4` while doing `$reactPromise  = \React\Promise\resolve($guzzlePromise);` will make `react/promise` convert it for you.

**Comment by socketman2016** [comment]
@WyriHaximus thanks for your reply
But there is a problem in this solution , now there is no difference between ```done()``` and ```then``` just ```done()``` returns ```void```

I want to have uncaught exceptions

```php
$guzzlePromise = new \GuzzleHttp\Promise\Promise();
$guzzlePromise
    ->then(function ($value) {
        throw new \Exception($value)
    });

$guzzlePromise->resolve('test');//Third party library

$reactPromise = \React\Promise\resolve($guzzlePromise)
    ->done();

``` 

As I use ```done()``` I expect ```Fatal error: Uncaught exception 'Exception' ``` but there is no fatal error just a rejected promise

I want to tell more details about my problem
I use a third party library based on ```\GuzzleHttp\Promise\Promise``` , My application handle errors with exceptions and I have a Uncaught exception handler to manage them , So sometimes I need to consume promise , something like ```done()``` to force promise throws exceptions instead of reject promise

1- How can I do this with ```React\Promise```
2- Can I do this in ```\GuzzleHttp\Promise\Promise```

**Comment by jsor** [comment]
You need to cast to a `React\Promise` **before** calling `then`on it.

```
$guzzlePromise = new \GuzzleHttp\Promise\Promise();

$reactPromise = \React\Promise\resolve($guzzlePromise)
    ->then(function ($value) {
        throw new \Exception($value)
    })
    ->done();

$guzzlePromise->resolve('test');//Third party library
```

**Comment by socketman2016** [comment]
@jsor thanks for your reply
I run your code but there is no ```Fatal error: Uncaught exception 'Exception'```
Where is my problem?! I check that ```throw new \Exception($value)``` is executed

**Comment by jsor** [comment]
Sorry, i replied too fast :/
Since `GuzzleHttp\Promise\Promise` provides no `done`, it's not possible to let rejections bubble out.

**Comment by socketman2016** [comment]
@jsor thank you
Can you please see this issue https://github.com/aws/aws-sdk-php/issues/1105

**Comment by jsor** [comment]
I've proposed #68 which uses `done()` instead of `then()`if available when resolving foreign thenables. This solves this issue when merged **and** `guzzlehttp/promises` implements `done()`.

**Comment by socketman2016** [comment]
So ```guzzlehttp/promises``` must be implement ```done()``` otherwise it dont works?
I understand right?

**Comment by WyriHaximus** [comment]
Correct

**Comment by socketman2016** [comment]
@jsor @WyriHaximus 
Thanks a lot

**Comment by socketman2016** [comment]
https://github.com/guzzle/promises/issues/44
