### ISSUE TITLE
Callback wrapper ?

### ISSUE THREAD

**Issue by Tatikoma** [reactphp/promise#69]
Hello, i writing code using reactphp promise library. I need to call some method and if promise failure then call this method again and again.

First time i written next code:

``` php
$instance = new SomeObject();
$onSuccess = function(){
    // do some useful things
};
$onFailure = function() use($instance, $onSuccess, &$onFailure){
    // retry function call
    $instance->method()->then($onSuccess, $onFailure);
};
$instance->method()->then($onSuccess, $onFailure);
```

This code have 2 problems:
1. "$instance->method()->then()"  is copypaste. When method has params i need to copypaste more and pass through "use" too much params.. 
2. If use this way, then i can write buggy code if accidentally reuse $onFailure because it passed via reference.

To avoid this issues i had re-written my code:

``` php
class CallbackWrapper{
    public $invoke;
    public $onSuccess;
    public $onFailure;

    public function invoke(){
        call_user_func($this->invoke);
    }
}

$instance = new SomeObject();

$callback = new CallbackWrapper();
$callback->onSuccess = function(){
    // do some useful things
};
$callback->onFailure = function() use($callback){
    $callback->invoke();
};
$callback->invoke = function() use($instance, $callback){
    $instance->method()->then($callback->onSuccess, $callback->onFailure);
};
$callback->invoke();
```

I see no issues with this code, but have a practical trouble - i need this helper in the majority of projects that uses promises. So maybe it makes sense to include such a helper to the promise library? Or may be i miss something and promise library has another ways to do it?

Sorry for my clumsy English.

**Comment by jsor** [comment]
Hi,

you could use a simple `retry` function which calls a promisor until the returned promise fulfills:

```php
function retry(callable $promisor) {
    return $promisor()
        ->otherwise(function() use ($promisor) {
            return retry($promisor);
        })
    ;
}

$instance = new SomeObject();
retry([$instance, 'method'])->done($onSuccess);
```

Note, that this will result in an infinite loop if the promise never fulfills :)
You could probably add a limit

**Comment by Tatikoma** [comment]
Yes, it can solve my task. I'm talking about that helper code like this might need to be included to promise library.

**Comment by jsor** [comment]
We're trying to keep react/promise focussed, encouraging creation of helper libraries around it. Examples are [clue/php-block-reac](https://github.com/clue/php-block-react) or [WyriHaximus/TickingPromise](https://github.com/WyriHaximus/TickingPromise). So, feel free to use my code snippet for that, but it is not going to be included into react/promise itself.

**Comment by Tatikoma** [comment]
Thank you for your answer fully answer my question.
