### ISSUE TITLE
callable param can not be null in the fastcgi environment

### ISSUE THREAD

**Issue by huyanping** [reactphp/promise#72]
```php
$defer = new React\Promise\Deferred();
$defer->promise();   
```

I found that this code can run normally in the cli environment, but it will trigger this error in the fast-cgi(php-fpm) environment.
php version: 5.4.41
error message:
```
PHP Catchable fatal error:  Argument 1 passed to React\Promise\Promise::__construct() must be callable, null given, called in vendor/react/promise/src/Deferred.php on line 25 and defined in vendor/react/promise/src/Promise.php on line 16 
```

I guess that this is an bug of php-fpm.

**Comment by clue** [comment]
This looks strange...

Which Promise version are you using? Can you show the output of `composer info`? Can you show us the code around `Deferred:25`? Can you make sure your vendor directory does not have any modifications (delete and reinstall)?

**Comment by huyanping** [comment]
Hi,
    I am sure that I didn't modify the code under my vendor directory. And I run the same script under different environment, the error will be triggered only in the fast-cgi(php-fpm) environment.

    Composer info: `react/promise         v2.2.1 A lightweight implementation of CommonJS Promises/A for PHP`

Deferred file:
```
<?php

namespace React\Promise;

class Deferred implements PromisorInterface
{
    private $promise;
    private $resolveCallback;
    private $rejectCallback;
    private $notifyCallback;
    private $canceller;

    public function __construct(callable $canceller = null)
    {
        $this->canceller = $canceller;
    }

    public function promise()
    {
        if (null === $this->promise) {
            $this->promise = new Promise(function ($resolve, $reject, $notify) {
                $this->resolveCallback = $resolve;
                $this->rejectCallback  = $reject;
                $this->notifyCallback  = $notify;
            }, $this->canceller); // `Deferred:25`
        }

        return $this->promise;
    }

    public function resolve($value = null)
    {
        $this->promise();

        call_user_func($this->resolveCallback, $value);
    }

    public function reject($reason = null)
    {
        $this->promise();

        call_user_func($this->rejectCallback, $reason);
    }

    public function notify($update = null)
    {
        $this->promise();

        call_user_func($this->notifyCallback, $update);
    }

    /**
     * @deprecated 2.2.0
     * @see Deferred::notify()
     */
    public function progress($update = null)
    {
        $this->notify($update);
    }
}
```

**Comment by clue** [comment]
> PHP Catchable fatal error: Argument 1 passed to React\Promise\Promise::__construct() must be callable, null given, called in vendor/react/promise/src/Deferred.php on line 25 and defined in vendor/react/promise/src/Promise.php on line 16

Thanks, but looking at the code you've posted, it clearly indicates we're in fact passing a `callable` and not a `null` value here. Can you make sure the absolute paths are correct and no other places (global installation?) interferes with this? Can you provide us a simple gist that helps reproducing the issue you're seeing? Does this problem persists if you execute this gist in a bare project without any other dependencies?

**Comment by jsor** [comment]
Closing for now. Feel free to reopen if needed.
