### ISSUE TITLE
Stable tags missing from Packagist

### ISSUE THREAD

**Issue by eerootsus** [reactphp/promise#85]
Currently only dev tags are available in Packagist thus installing anything dependent on your stable tags isn't possible.

**Comment by clue** [comment]
Thanks for reporting! Not sure what happened here, but I can reproduce this. We'll look into this shortly!

**Comment by WyriHaximus** [comment]
Tags are back

**Comment by eerootsus** [comment]
Super! Thanks!

**Comment by sui77** [comment]
works :) thank you

**Comment by jsor** [comment]
Thanks @WyriHaximus!
