### ISSUE TITLE
Missing example code

### ISSUE THREAD

**Issue by UlrichEckhardt** [reactphp/promise#91]
Hi!

I'm trying to evaluate react/promise as alternative to guzzlehttp/promise, but I can't seem to find a way to reap a promise, i.e. wait for it to be resolved and get at the according result. All I can do is to tell it what to do with the result (using then() or done()), but that just gives me another promise which is just as useful as the one I had.

I'm sure it can be done, but it's not obvious, or at least not obvious to someone who doesn't have certain background knowledge. I'd be happy if you just added a few examples that people can actually execute or use as base for their own development.

Thanks!

Uli

**Comment by jsor** [comment]
There is no support for awaiting a promise in react/promise itself. But you could use https://github.com/clue/php-block-react.

**Comment by clue** [comment]
I'm not sure what you're trying to achieve, so perhaps a simple gist of this could help here?

If you're working with async code, you will likely want to "react" to when a promise is resolved instead of "awaiting" it. The former allows other async code to execute while the latter implies blocking/waiting for single operation.

**Comment by stefanotorresi** [comment]
the OP probably needs an example showing how to achieve the same behaviour that Guzzle provides with [Promise::wait()](https://github.com/guzzle/promises#synchronous-wait), which is exactly what `clue/php-block-react` provides.

**Comment by UlrichEckhardt** [comment]
Hi!

Sorry for the silence, I was busy doing other things. In any case, thanks for the suggestions, I now think that `reactphp/promise` might not be the thing I'm looking for (or at least not on its own). Anyhow, the reason I was asking for examples was that an example often help understanding things in a different way than formal documentation. The latter explains the details, but it has a relatively high entry barrier. Examples have a lower entry barrier, but they don't explain details. So, it's just a suggestion to add some examples in order to help people like me that don't have an inside view (yet).

Cheers!

Uli

**Comment by jsor** [comment]
Closing for now. Feel free to reopen if you have any further questions.
